### ISSUE TITLE
Issue with method declaration on 3 lines

### ISSUE THREAD

**Issue by DrySs** [gwarnants/FunctionList-PHP-Patch#3]
Hi there,

Many thanks for you parser, this is working really great and was looking for that since a long time ;)

I have an issue with a method declaration made... on 3 lines.
Yes, this is ugly, but I need to use tierce software (PrestaShop), which has some methods declaration on 2 or 3 lines (because of lots arguments).

For example, this declaration is not found by your parser:
> public function myFunc($arg1, 
> $arg2,
> $arg3)
> {

But with 1 or 2 lines, this is working:
> public function myFunc($arg1, 
> $arg2)
> {

Any idea?
Thanks,
Philippe

**Comment by ge0ffray** [comment]
Hello Philippe,

Thanks for your report. I just commit a little fix that should now correctly parse functions with multi-line arguments.

Regards,
Geoffray

**Comment by DrySs** [comment]
Yeah! It's working very well, many thanks Geoffray :+1:
